// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHOxed7DhHnPaTZgGhwe20uWSOMX_M3Mw',
    appId: '1:962555135029:web:3eda877e6080a1c79d9d7c',
    messagingSenderId: '962555135029',
    projectId: 'flutter-hw32',
    authDomain: 'flutter-hw32.firebaseapp.com',
    storageBucket: 'flutter-hw32.firebasestorage.app',
    measurementId: 'G-V40GQS4N7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQf3TGPN3C54UZe57O5ruL40j7-ZJWHDo',
    appId: '1:962555135029:android:5ab652303f3880a99d9d7c',
    messagingSenderId: '962555135029',
    projectId: 'flutter-hw32',
    storageBucket: 'flutter-hw32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbkmgFaBQb4HVW00p-2IO6nmGDPZJBRkA',
    appId: '1:962555135029:ios:9891c6ece431b7349d9d7c',
    messagingSenderId: '962555135029',
    projectId: 'flutter-hw32',
    storageBucket: 'flutter-hw32.firebasestorage.app',
    iosClientId: '962555135029-6pt1f9582ulnp5ea8rivstk2pmfgjb6f.apps.googleusercontent.com',
    iosBundleId: 'com.hw32.hw32',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbkmgFaBQb4HVW00p-2IO6nmGDPZJBRkA',
    appId: '1:962555135029:ios:9891c6ece431b7349d9d7c',
    messagingSenderId: '962555135029',
    projectId: 'flutter-hw32',
    storageBucket: 'flutter-hw32.firebasestorage.app',
    iosClientId: '962555135029-6pt1f9582ulnp5ea8rivstk2pmfgjb6f.apps.googleusercontent.com',
    iosBundleId: 'com.hw32.hw32',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHOxed7DhHnPaTZgGhwe20uWSOMX_M3Mw',
    appId: '1:962555135029:web:d71b2d8b19a3c6c69d9d7c',
    messagingSenderId: '962555135029',
    projectId: 'flutter-hw32',
    authDomain: 'flutter-hw32.firebaseapp.com',
    storageBucket: 'flutter-hw32.firebasestorage.app',
    measurementId: 'G-H74424JVWD',
  );
}
